package main

import "text/template"

var srcTempl = template.Must(template.New("main.go").Parse(`// This file is generated by vetgen.
// Do NOT modify this file.
//
// You can run this tool with go vet such as:
//	go vet -vettool=$(which myvet) pkgname
package main

import (
	"golang.org/x/tools/go/analysis/unitchecker"
	"github.com/gostaticanalysis/vetgen/analyzers"
	{{range .}}
	"{{.ImportPath}}" // add by vetgen
	{{- end}}
)

var myAnayzers = []*analysis.Analyzer{
	{{range . -}}
	{{.Pkg}}.Analyzer,
	{{end}}
}

func main() {
	unitchecker.Main(append(
		analyzers.Recommend(),
		myAnayzers...,
	))
}`))
